 INSERT INTO estado (codigo_ibge,sigla,nome) VALUES(12,'AC','Acre');  
 INSERT INTO estado (codigo_ibge,sigla,nome) VALUES(27,'AL','Alagoas');  
 INSERT INTO estado (codigo_ibge,sigla,nome) VALUES(13,'AM','Amazonas');
 INSERT INTO estado (codigo_ibge,sigla,nome) VALUES(16,'AP','Amapá');
 INSERT INTO estado (codigo_ibge,sigla,nome) VALUES(29,'BA','Bahia');
 INSERT INTO estado (codigo_ibge,sigla,nome) VALUES(23,'CE','Ceará');
 INSERT INTO estado (codigo_ibge,sigla,nome) VALUES(53,'DF','Distrito Federal');
 INSERT INTO estado (codigo_ibge,sigla,nome) VALUES(32,'ES','Espírito Santo');
 INSERT INTO estado (codigo_ibge,sigla,nome) VALUES(52,'GO','Goiás');
 INSERT INTO estado (codigo_ibge,sigla,nome) VALUES(21,'MA','Maranhão');
 INSERT INTO estado (codigo_ibge,sigla,nome) VALUES(31,'MG','Minas Gerais');
 INSERT INTO estado (codigo_ibge,sigla,nome) VALUES(50,'MS','Mato Grosso do Sul');
 INSERT INTO estado (codigo_ibge,sigla,nome) VALUES(51,'MT','Mato Grosso');
 INSERT INTO estado (codigo_ibge,sigla,nome) VALUES(15,'PA','Pará');
 INSERT INTO estado (codigo_ibge,sigla,nome) VALUES(25,'PB','Paraíba');
 INSERT INTO estado (codigo_ibge,sigla,nome) VALUES(26,'PE','Pernambuco');
 INSERT INTO estado (codigo_ibge,sigla,nome) VALUES(22,'PI','Piauí');
 INSERT INTO estado (codigo_ibge,sigla,nome) VALUES(41,'PR','Paraná');
 INSERT INTO estado (codigo_ibge,sigla,nome) VALUES(33,'RJ','Rio de Janeiro');
 INSERT INTO estado (codigo_ibge,sigla,nome) VALUES(24,'RN','Rio Grande do Norte');
 INSERT INTO estado (codigo_ibge,sigla,nome) VALUES(11,'RO','Rondônia');
 INSERT INTO estado (codigo_ibge,sigla,nome) VALUES(14,'RR','Roraima');
 INSERT INTO estado (codigo_ibge,sigla,nome) VALUES(43,'RS','Rio Grande do Sul');
 INSERT INTO estado (codigo_ibge,sigla,nome) VALUES(42,'SC','Santa Catarina');
 INSERT INTO estado (codigo_ibge,sigla,nome) VALUES(28,'SE','Sergipe');
 INSERT INTO estado (codigo_ibge,sigla,nome) VALUES(35,'SP','São Paulo');
 INSERT INTO estado (codigo_ibge,sigla,nome) VALUES(17,'TO','Tocantins');